详情见下
DGP-Studio/Snap.Hutao.Docs pull request #109
Opened 2024-02-22 10:40 UTC by Mikachu2333

1. 更新了胡桃文档中的md指向文件引用，使之直接指向对应的小标题
2. 区分了反引号和双引号，使反引号只作用与代码块

2024-02-22 22:14 UTC, Masterain98 requested changes

2024-02-22 22:14 UTC, Masterain98 commented on docs/zh/advanced/FAQ.md
> +  - 你亦可以手动下载并安装[胡桃的相关依赖](dependency.md#手动安装依赖项)
无子章节信息的文档加 `#` 没有意义

2024-02-22 22:14 UTC, Masterain98 commented on docs/zh/advanced/FAQ.md
> +1. 手动下载并安装[胡桃的相关依赖](dependency.md#手动安装依赖项)
无子章节信息的文档加 `#` 没有意义

2024-02-22 22:14 UTC, Masterain98 commented on docs/zh/features/achievements.md
> +- 胡桃工具箱使用 [UIAF 统一可交换成就标准](https://uigf.org/zh/standards/UIAF.html) 来储存用户的成就数据
词性不对，UIAF 标准是一种数据格式，而不是一种储存方法或储存介质

2024-02-22 22:14 UTC, Masterain98 commented on docs/zh/project.md
该文件有 Git 冲突

2024-02-22 22:14 UTC, Masterain98 commented on docs/zh/quick-start.md
> +- 在安装过程中，如果出现任意以下错误之一，请参考文章[手动安装依赖项](advanced/dependency.md#手动安装依赖项)解决，该问题来源是Windows无法自动安装所需要的框架环境
不需要 #

2024-02-22 22:14 UTC, Masterain98 commented on docs/zh/side-load.md
该文件中有中文双引号用反了的情况

2024-02-23 11:08 UTC, Mikachu2333 commented on docs/zh/advanced/FAQ.md
> +  - 你亦可以手动下载并安装[胡桃的相关依赖](dependency.md#手动安装依赖项)
只是为了格式统一罢了

2024-02-23 11:29 UTC, Mikachu2333 commented on docs/zh/side-load.md
我的，马上修

2024-02-23 11:29 UTC, Mikachu2333 commented on docs/zh/advanced/FAQ.md
> +1. 手动下载并安装[胡桃的相关依赖](dependency.md#手动安装依赖项)
同上，为了格式统一

2024-02-23 11:29 UTC, Mikachu2333 commented on docs/zh/advanced/FAQ.md
> +  - 你亦可以手动下载并安装[胡桃的相关依赖](dependency.md#手动安装依赖项)
此外，如果今后文档因为增加内容导致排版变动时，以 `#` 作为跳转的超链接也可以避免临时返工。

2024-02-24 14:12 UTC, Mikachu2333 commented
所有冲突等均已解决完毕

2024-02-24 14:13 UTC, Mikachu2333 commented
以根据建议修正dependency.md的#号引用

2024-02-24 14:38 UTC, qhy040404 approved these changes

2024-02-24 15:46 UTC, Masterain98 approved these changes

2024-02-24 16:06 UTC, merged