add a chapter in faq for download net error
DGP-Studio/Snap.Hutao.Docs pull request #113
Opened 2024-03-01 09:27 UTC by Mikachu2333

besides, format some chapter

2024-03-01 21:58 UTC, Masterain98 requested changes

2024-03-01 21:58 UTC, Masterain98 commented on docs/zh/support-us.md
> +如果您是公司主体并希望通过您的产品帮助到 Snap Hutao，请通过 [support@dgp-studio.cn](mailto://support@dgp-studio.cn) 邮箱与我们取得联系。我们会将全部的赞助商显示在我们的 [首页](README.md#赞助商) 中。
中文前后若不接英文则不要加空格，加了后前端也不会渲染

2024-03-01 21:58 UTC, Masterain98 commented on docs/zh/advanced/exceptions.md
> +因特殊网络（如校园网）所致，请尝试更换网络。
实际原因未知

2024-03-01 21:58 UTC, Masterain98 commented on docs/zh/advanced/exceptions.md
> +由于网络波动或者特殊网络的防火墙配置阻断了胡桃的数据所致，请尝试将校园网更换为手机热点或其他可信网络。
不要使用指向性强的指导，手机热点不是一个好的方法

2024-03-01 21:58 UTC, Masterain98 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理，请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)（注：`SteamCommunity302` 等加速器软件也需要注意此问题）
需要限定是使用了代理网络的加速器类程序

2024-03-02 00:28 UTC, qhy040404 requested changes

2024-03-02 00:28 UTC, qhy040404 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理，请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)（注：`SteamCommunity302` 等加速器软件也需要注意此问题）
302是反代+hosts，不会修改系统代理，与loopback无关

2024-03-02 02:54 UTC, Mikachu2333 commented on docs/zh/advanced/exceptions.md
> +因特殊网络（如校园网）所致，请尝试更换网络。
我昨晚试了试基本是与网络有关，只要换用流量立即恢复正常

2024-03-02 02:54 UTC, Mikachu2333 commented on docs/zh/advanced/exceptions.md
> +由于网络波动或者特殊网络的防火墙配置阻断了胡桃的数据所致，请尝试将校园网更换为手机热点或其他可信网络。
呜，那我换一个模糊点的吧

2024-03-02 02:54 UTC, Mikachu2333 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理，请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)（注：`SteamCommunity302` 等加速器软件也需要注意此问题）
ok

2024-03-02 02:55 UTC, Mikachu2333 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理，请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)（注：`SteamCommunity302` 等加速器软件也需要注意此问题）
好的

2024-03-02 02:55 UTC, Mikachu2333 commented on docs/zh/support-us.md
> +如果您是公司主体并希望通过您的产品帮助到 Snap Hutao，请通过 [support@dgp-studio.cn](mailto://support@dgp-studio.cn) 邮箱与我们取得联系。我们会将全部的赞助商显示在我们的 [首页](README.md#赞助商) 中。
那我再删了

2024-03-02 08:52 UTC, Masterain98 approved these changes

2024-03-02 09:00 UTC, qhy040404 approved these changes

2024-03-02 09:01 UTC, merged