update
DGP-Studio/Snap.Hutao.Docs pull request #133
Opened 2024-06-20 16:44 UTC by Mikachu2333

etc.

2024-06-20 17:37 UTC, qhy040404 requested changes

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/advanced/FAQ.md
> +### 如何通过网络代理（VPN）使用胡桃工具箱
没必要写明vpn

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理（VPN），请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)
同上

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/development/contribute.md
> -1. 下载并安装 [Visual Studio 2022 Community](https://visualstudio.microsoft.com/downloads/)
保持原样，让用户自己点下载

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/development/contribute.md
> +一旦你的代码被合并进 `develop` 或 `main` 分支，一个 GitHub Actions 脚本将自动运行以构建所在分支的最新解决方案，并以 `Snap Hutao Alpha` 命名并上传，`feat` 类分支仅在 `push` 事件发生时构建 `Alpha` 版本。
所以push都会构建alpha，只是除了main和develop外，feat也会打包。其他只验证可构建性

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/features/feedback-center.md
> +  - Snap Hutao 主要功能
这些都是链接，易误解

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/features/feedback-center.md
> +  - Snap Hutao 当前的问题
项目议题

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/features/game-launcher.md
> +- 在您也可以固定胡桃到任务栏，通过右击快速启动栏中胡桃应用程序的图标以快速启动游戏
这个无了

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/quick-start.md
> -
这一块再放一个大版本吧 1.11再删

2024-06-20 17:37 UTC, qhy040404 commented on docs/zh/side-load.md
这页感觉可以删了，没用

2024-06-21 02:27 UTC, Mikachu2333 commented on docs/zh/advanced/FAQ.md
> +### 如何通过网络代理（VPN）使用胡桃工具箱
故意的，很多人搜索的时候第一反应就是搜VPN，比如某些群友，所以才故意加的

2024-06-21 02:27 UTC, Mikachu2333 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理（VPN），请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)
同上

2024-06-21 02:27 UTC, Mikachu2333 commented on docs/zh/development/contribute.md
> -1. 下载并安装 [Visual Studio 2022 Community](https://visualstudio.microsoft.com/downloads/)
行

2024-06-21 04:54 UTC, Mikachu2333 commented on docs/zh/features/feedback-center.md
> +  - Snap Hutao 主要功能
不知道咋改，这里只是把原本的换了个排版，内容没咋变（

2024-06-21 04:57 UTC, Mikachu2333 commented on docs/zh/side-load.md
不会删，不知道删了以后是否影响其他页面的超链接引用，留个天雨了

2024-06-21 05:02 UTC, Mikachu2333 commented on docs/zh/quick-start.md
> -
彳亍

2024-06-21 07:36 UTC, qhy040404 commented on docs/zh/advanced/FAQ.md
> +### 如何通过网络代理（VPN）使用胡桃工具箱
加你妈

2024-06-21 07:36 UTC, qhy040404 commented on docs/zh/advanced/exceptions.md
> +如果你使用了网络代理（VPN），请务必检查是否[解除了 Windows 容器 Loopback 限制](FAQ.md#如何通过网络代理使用胡桃工具箱)
同上你妈

2024-06-21 07:37 UTC, qhy040404 commented on docs/zh/development/contribute.md
> -1. 下载并安装 [Visual Studio 2022 Community](https://visualstudio.microsoft.com/downloads/)
官网上没有installer字样

2024-06-21 08:10 UTC, Masterain98 requested changes

2024-06-21 08:10 UTC, Masterain98 commented on docs/zh/features/game-launcher.md
> +- 点击右上角的“启动游戏”按钮，胡桃会从对应的米哈游官方服务器自动下载并完成部署，之后将自动启动游戏
为什么要用“部署”这个词？这一流程完全没有“部署”这一操作，应用就是最好的词汇

2024-06-21 08:10 UTC, Masterain98 commented on docs/zh/features/game-launcher.md
> +- 点击“启动游戏-游戏选项-进程”选项卡
什么叫选项卡？没有这种东西能点击

2024-06-21 08:10 UTC, Masterain98 commented on docs/zh/features/hutao-passport.md
> +   - 你可以通过该方法长期地间断性免费使用胡桃云
去掉“间断性”

2024-06-21 08:10 UTC, Masterain98 commented on docs/zh/features/hutao-settings.md
> +2. 在桌面上创建一个以管理员身份启动胡桃的 lnk 快捷方式
完全没有必要写 lnk

2024-06-21 08:11 UTC, Masterain98 requested changes

2024-06-21 08:11 UTC, Masterain98 commented on docs/zh/features/game-launcher.md
> +- 在“启动游戏-进程”选项卡中，启用“启动参数” 功能，点击展开后你可以设置更多细节：
去掉选项卡三字

2024-06-21 09:47 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +- 点击“启动游戏-游戏选项-进程”选项卡
那改成“定位到”

2024-06-21 09:49 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +- 点击右上角的“启动游戏”按钮，胡桃会从对应的米哈游官方服务器自动下载并完成部署，之后将自动启动游戏
因为完成应用我认为是重复，那我改成应用吧，把完成删除

2024-06-21 09:49 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +- 在“启动游戏-进程”选项卡中，启用“启动参数” 功能，点击展开后你可以设置更多细节：
111

2024-06-21 09:51 UTC, Mikachu2333 commented on docs/zh/features/hutao-passport.md
> +   - 你可以通过该方法长期地间断性免费使用胡桃云
长期一般是时间长、不间断吧……还是感觉得换个措辞

删了

2024-06-21 09:53 UTC, Mikachu2333 commented on docs/zh/features/hutao-settings.md
> +2. 在桌面上创建一个以管理员身份启动胡桃的 lnk 快捷方式
对标之前的文档说法“以管理员身份启动胡桃的 PowerShell 快捷方式”

2024-06-21 10:06 UTC, Mikachu2333 commented on docs/zh/development/contribute.md
> -1. 下载并安装 [Visual Studio 2022 Community](https://visualstudio.microsoft.com/downloads/)
最终的结果就是安装了installer，微软的下载页叫VS，下载的程序名是vsSetuper，最后安装完成叫installer，因此我就直接写了installer……

2024-06-21 10:07 UTC, Mikachu2333 commented on docs/zh/advanced/FAQ.md
> +### 如何通过网络代理（VPN）使用胡桃工具箱
> 加你妈

好吧……那能不能搞个同义词之类的出来，最后效果就是用户看不到这个词，但是搜索的时候可以定位到这个条目

2024-06-21 10:22 UTC, qhy040404 commented on docs/zh/features/game-launcher.md
> +- 点击任务栏右下角的胡桃图标（通常会被系统自动收纳），选择启动游戏
默认收纳

2024-06-21 10:31 UTC, qhy040404 requested changes

2024-06-21 10:31 UTC, qhy040404 commented on docs/zh/features/game-launcher.md
> +- 点击任务栏右下角的胡桃图标（通常会被系统自动收纳），选择启动游戏
默认收纳

2024-06-21 10:31 UTC, qhy040404 commented on docs/zh/side-load.md
这个文件直接删掉

2024-06-21 10:50 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +- 点击任务栏右下角的胡桃图标（通常会被系统自动收纳），选择启动游戏
111

2024-06-21 10:50 UTC, Mikachu2333 commented on docs/zh/side-load.md
@Masterain98

2024-06-21 10:59 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +- 点击任务栏右下角的胡桃图标（通常会被系统自动收纳），选择启动游戏
并不认为这是一个问题，因在图标极少时不会被系统自动收纳。

2024-06-21 17:34 UTC, Masterain98 requested changes

2024-06-21 17:34 UTC, Masterain98 commented on docs/zh/development/contribute.md
> +- 所有不是从本项目其它分支发起的 Pull Request 都只被允许合并进 `develop` 分支
这个”本“就很没有必要，完全是为了改而改

2024-06-21 17:34 UTC, Masterain98 commented on docs/zh/development/contribute.md
> +1. 下载 [Visual Studio Setup](https://visualstudio.microsoft.com/downloads/) 以安装 `Visual Studio 2022 Community`
改成回来的或者改成 Visual Studio

2024-06-21 17:34 UTC, Masterain98 commented on docs/zh/side-load.md
删掉

2024-06-21 17:34 UTC, Masterain98 commented on docs/zh/development/contribute.md
> +你可以在 [Alpha 流水线](https://github.com/DGP-Studio/Snap.Hutao/actions/workflows/alpha.yml) 中找到全部的编译记录。
你给一个 yml 配置文件的地址有什么用途？

2024-06-22 01:35 UTC, qhy040404 commented on docs/zh/development/contribute.md
> +1. 下载 [Visual Studio Setup](https://visualstudio.microsoft.com/downloads/) 以安装 `Visual Studio 2022 Community`
这个确实给的没毛病

2024-06-22 01:36 UTC, qhy040404 commented on docs/zh/development/contribute.md
> +你可以在 [Alpha 流水线](https://github.com/DGP-Studio/Snap.Hutao/actions/workflows/alpha.yml) 中找到全部的编译记录。
这个确实给的没毛病

2024-06-22 02:23 UTC, Mikachu2333 commented on docs/zh/development/contribute.md
> +你可以在 [Alpha 流水线](https://github.com/DGP-Studio/Snap.Hutao/actions/workflows/alpha.yml) 中找到全部的编译记录。
直接跳转到运行了alpha构建的页面啊，我也认为没有问题
![图片](https://github.com/DGP-Studio/Snap.Hutao.Docs/assets/63829496/28499356-9100-4c98-a018-0a41596477b0)

2024-06-22 02:23 UTC, Mikachu2333 commented on docs/zh/side-load.md
行

2024-06-22 02:26 UTC, Mikachu2333 commented on docs/zh/development/contribute.md
> +- 所有不是从本项目其它分支发起的 Pull Request 都只被允许合并进 `develop` 分支
没有“本”读起来怪怪的……

那我就再删了……

2024-06-22 02:29 UTC, Mikachu2333 commented on docs/zh/development/contribute.md
> +你可以在 [Alpha 流水线](https://github.com/DGP-Studio/Snap.Hutao/actions/workflows/alpha.yml) 中找到全部的编译记录。
另，yml的原始地址是在某个branch里面的，这只是分类而已

2024-06-23 05:13 UTC, qhy040404 requested changes

2024-06-23 05:13 UTC, qhy040404 commented on docs/zh/advanced/FAQ.md
> +:::
我都不知道有什么意义

2024-06-23 05:13 UTC, qhy040404 commented on docs/zh/development/contribute.md
> +1. 下载 [Visual Studio](https://visualstudio.microsoft.com/downloads/) 以安装 `Visual Studio 2022 Community`
草你妈的改回去

2024-06-23 05:22 UTC, Mikachu2333 commented on docs/zh/advanced/FAQ.md
> +:::
你问希尔，他说要强调各种方式并非绝对有效……

2024-06-24 17:52 UTC, Masterain98 commented on docs/zh/features/game-launcher.md
> +      - 本选项不适用于笔记本触摸屏，仅供串流使用
怎么可能触屏不能用

2024-06-25 12:02 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +      - 本选项不适用于笔记本触摸屏，仅供串流使用
我就用不了，我是触屏

希望表达的原义大概是，对希望在触屏笔记本电脑上以手机的方式进行游玩的用户并不适用。大概是这个意思吧

2024-06-25 12:04 UTC, Mikachu2333 commented on docs/zh/features/game-launcher.md
> +      - 本选项不适用于笔记本触摸屏，仅供串流使用
详见2024.3.15的聊天记录，从23:48开始

2024-06-25 18:22 UTC, Masterain98 commented on docs/zh/features/game-launcher.md
> +      - 本选项不适用于笔记本触摸屏，仅供串流使用
我能用

2024-06-27 04:47 UTC, Masterain98 commented
@qhy040404 看看英文版还有什么要改的

2024-06-27 04:56 UTC, qhy040404 approved these changes

2024-06-29 07:17 UTC, Masterain98 approved these changes

2024-06-29 07:18 UTC, merged