Correct typo
DGP-Studio/Snap.Hutao.Docs pull request #154
Opened 2024-10-14 07:56 UTC by Mikachu2333

etc

2024-10-22 09:37 UTC, Mikachu2333 commented
@Masterain98 可以审核了

本更新含有以下内容：
1. HoYoLab全文替换为HoYoLAB，与官方Google Play里面的名称保持一致
2. 错误的英文中文符号替换与标点改正
3. 超链接格式统一，即 `XXX 超链接 XXX`，前后空格各一
4. 软件错误显示网络状况的解释说明
5. 笔误更正

2024-10-22 10:00 UTC, Mikachu2333 commented
新加一条，修正歧义

2024-10-22 19:42 UTC, Masterain98 requested changes
超链接前后不需要空格，中英文之间空格即可

2024-10-27 10:23 UTC, Masterain98 approved these changes

2024-10-27 10:23 UTC, merged