update account
DGP-Studio/Snap.Hutao.Docs pull request #155
Opened 2024-10-14 07:57 UTC by Mikachu2333

etc

2024-10-14 08:54 UTC, Mikachu2333 commented
需要进一步的格式化帮助……

2024-10-17 14:06 UTC, BTMuli commented
> 需要进一步的格式化帮助……

https://github.com/vuepress/ecosystem/issues/275

2024-10-22 04:46 UTC, Mikachu2333 commented
@Masterain98 虽然原始md文档写的很丑，但是内容和格式已经没问题了。

> vuepress/ecosystem#275

这玩意看起来一时半会没戏，暂时妥协了。换用了红蓝两色进行强调与提示

2024-10-22 05:03 UTC, Masterain98 commented
站点主题色应该为 `#f26d6d`

2024-10-22 05:08 UTC, Masterain98 requested changes
![image](https://github.com/user-attachments/assets/d46ac5c3-c656-4d6c-a546-7208ce7e8e79)

这里没必要红色

2024-10-22 05:12 UTC, Mikachu2333 commented
fixed

2024-10-22 06:42 UTC, Masterain98 approved these changes
文档本身没有什么问题了，主题色的问题之后再修复吧

2024-10-22 06:42 UTC, merged