docs: improve README
DGP-Studio/Snap.Hutao.Docs pull request #189
Opened 2024-12-15 11:04 UTC by Mister-Hope

2024-12-15 11:53 UTC, BTMuli approved these changes

2024-12-15 13:22 UTC, BTMuli requested changes

2024-12-15 13:22 UTC, BTMuli commented on README.md
> +- Install [latest LTS version of NodeJS](https://nodejs.org/en/download/)
package.json 内有 engine 字段，是不是也得同步更新一下？

2024-12-15 14:16 UTC, Mister-Hope commented on README.md
> +- Install [latest LTS version of NodeJS](https://nodejs.org/en/download/)
Engine 目前的要求就是最低 18.19，这个在上一个PR已经更新了，对于贡献者来说，应该首选最新的 LTS 版本而不是最低版本，这没有冲突。

2024-12-16 00:10 UTC, BTMuli approved these changes

2024-12-16 00:49 UTC, merged